modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="1.0.0"
displayName="Miners Dream Mod"
authors="Tino"
description='''
A mod that adds the Miners Dream.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)" # <-- THIS LINE IS FIXED
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)" # <-- THIS LINE IS FIXED
    ordering="NONE"
    side="BOTH"
